export default [
    {
      id: "1",
      name: "Sid Majeti",
      role: "President",
      description: "Hi everyone! My name is Sid Majeti and I am a rising junior majoring in computer science. I have been a part of Coders SB ever since my freshman year and have met some of my closest friends through Coders! In my free time I like to play basketball and go on runs along the beach. Hope to you see you guys soon at our events!",
      image: "Officers/sid.jpg",
    },
    {
        id: "2",
        name: "David Wang",
        role: "Vice President",
        description: "Hi my name is David. I'm a second-year computer science major. Some of the topics I'm most interested in exploring are computer vision and machine learning.  In my free time I enjoy rock climbing, video games (Apex legends and league 💀), and reading manga/watching anime. Recently I've also had a fun time learning how to cook.",
        image: "Officers/david.jpg",
    },
    {
        id: "3",
        name: "Vidit Agrawal",
        role: "General Officer",
        description:"Hey everyone! My name is Vidit and I'm a sophomore majoring in Computer Science. I'm super excited to meet and get to know everyone this year! A little bit about me: I love to hike and do outdoorsy things like paddleboarding, kayaking, going to the beach, etc. I also really like to listen to music and hang out with friends        ",
        image: "Officers/vidit.jpg",
    },
    {
        id: "4",
        name: "Elaine Ho",
        role: "General Officer",
        description:"Hello! my name is Elaine Ho and I am a rising sophomore majoring in Computer Science! During my free time, I love embroidering, sewing clothes, acrylic painting, and watching kdramas.",
        image: "Officers/elaine.jpg",
    },
    {
        id: "5",
        name: "Sangita Kunapuli",
        role: "General Officer",
        description:"Hi my name is Sangita! I'm a third year undergrad studying computer science! In my free time, I enjoy exploring new music, singing a cappella, and bullet journaling.",
        image: "Officers/sangita.jpg",
    },
    {
        id: "6",
        name: "Aditi Phatak",
        role: "General Officer",
        description:"Hi my name is Aditi Phatak and I am a second year undergraduate majoring in computer science. During my free time, I enjoy crocheting, going on sunrise runs at the beach, and binge watching shows.",
        image: "Officers/aditi.jpg",
    },
    {
        id: "7",
        name: "Ethan Yuan",
        role: "General Officer",
        description:"Hey all! My name is Ethan Yuan and I’m a first year Computer Science major! In my free time, I love working out, playing basketball, and vibing to music. Looking forward to having a great year!",
        image: "Officers/ethan.jpg",
    },
    {
        id: "8",
        name: "Jennifer Zhu",
        role: "General Officer",
        description:"Hi! My name is Jennifer Zhu and I'm a freshmen majoring in Computer Science. In my spare time, I love painting, reading, and grabbing coffee with friends. Excited to meet everyone!",
        image: "Officers/jennifer.jpg",
    },
    {
        id: "9",
        name: "Rohil Shah",
        role: "General Officer",
        description:"Hey everyone! My name is Rohil Shah and I'm a first-year majoring in computer science. I'm also interested in physics, linguistics, and mathematics, especially their overlap with CS. In my free time I enjoy reading and learning languages.",
        image: "Officers/rohil.JPG",
    },
    {
        id: "10",
        name: "Shamita Gurusu",
        role: "General Officer",
        description:"Hello everyone! My name is Shamita and I am a second-year computer science major interested in NLP(Natural Language Processing) and computer vision. I am an avid sunset and chocolate connoisseur and love all things outdoors(hiking, diving, kayaking, etc.). Looking forward to meeting y'all this year!",
        image: "Officers/shamita.png",
    },
    {
        id: "11",
        name: "Eugene Wong",
        role: "General Officer",
        description:"Hihi! My name is Eugene and I am a first-year computer science major. Any free time I have, you can expect me to be cubing, playing TFT, drinking boba, and binging k-dramas. It's great to meet you all!",
        image: "Officers/eugene.jpg",
    }
  ];
  